
development:
  adapter: postgresql
  host: localhost
  timeout: 5000
  encoding: unicode
  database: scrap-app
  pool: 5
  username : user1
  password: password

test:
  adapter: postgresql
  host: localhost
  timeout: 5000
  encoding: unicode
  database: scrap-app
  pool: 5
  username : user1
  password: password

production:
  adapter: postgresql
  host: localhost
  timeout: 5000
  encoding: unicode
  database: scrap-app
  pool: 5
  password: