# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b6bf3c11f41d26549d6533e59c1e420ec4c7167d1bafe3f434051393042dedcb2a8ec33dd3f4d20a8df1fa39c058d213b2682b7f68ae8856ef36ea73811c55

test:
  secret_key_base: b230edbb59eae554d7414e1f7ea7f43b4b379ca6bc59f1f851801126bc47b4f2d89707dcb82f79120604723896c712ec3b27c5c9bdbc9bc59392d1dcfa182ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
